### ISSUE TITLE
destroy() discussion with partial fix

### ISSUE THREAD

**Issue by nikrowell** [ayamflow/standalone-shader#5]
I noticed the `destroy()` method needs to be updated slightly to work correctly:
```js
destroy() {
    const gl = this.gl // moved to top of function
    this.stop() // cancel raf and prevent bind calls on deleted buffers
    // ... rest of function
}
```
The above works fine if you call `sd.destroy()` immediately after `sd.start()`, however, I didn't submit as a patch because there are some related issues that I wasn't sure how to elegantly address.

If you were to call destroy _before_ start in the first demo, you get WebGL warnings for "attempt to bind a deleted buffer". Makes sense, and resolved by adding a `this.gl.isBuffer(this.positionBuffer)` check before enqueuing update, but I'm trying to think of a good edge case that would need this. Perhaps this is just a monkey bug.

Textures also need some considerations when destroying. If destroy is called before the internal onload, self.update() will try to bind deleted textures. Better to refactor the onload listener so it can be removed in destroy, or add a check for `this.gl.isTexture(this.texture)` before updating?

**Comment by ayamflow** [comment]
Good points!
I think you listed all the good solutions: using `gl.isBuffer` before deleting the buffer, and refactoring the onload listener (should have been done sooner tbh since it might result in a leak).

I can picture use cases for these fixes - for instance a shader created upon page navigation but the back button was pressed before `start` was ever called.

**Comment by nikrowell** [comment]
Cool - thanks! I'll take a pass at adding those checks.

**Comment by nikrowell** [comment]
Closing. Discussion moved to #6
